baseURL: https://aman-sharma-lbs.netlify.app/
languageCode: en-us
title: Aman
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Learn more
    subtitle: |-
      I AM BRITISH AND CURRENTLY STUDYING FOR MY MASTERS AT LONDON BUSINESS SCHOOL. WELCOME TO MY PORTFOLIO WEBSITE!
    title: Hello! I am Aman.
  blog: {}
  contact:
    address:
      - city: Maidenhead
        country: United Kingdom
        street: Cox Green Road
        title: Address
    buttonClear: Start again
    buttonSend: Say Hello!
    email:
      - email: amanakshay@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (079) 158-78963
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: Aman
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/AmanSharmaGitHub
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/amanakshaysharma
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Read More
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: portfolio website
    title: AMAN
  tiles:
    enable: yes
    showcase:
      - image: london-business-school-Campus.jpeg
        subtitle: Snapshot of my story so far
        title: About Me
        url: blogs/amansharma
      - image: pic02.jpg
        subtitle: Applied Statistics in R
        title: Homework 1
        url: blogs/homeworkone
      - image: pic03.jpg
        subtitle: Applied Statistics in R
        title: Homework 2
        url: blogs/homeworktwo
      - image: pic04.jpg
        subtitle: Applied Statistics in R
        title: Homework 3
        url: blogs/homeworkthree
  
  two:
    buttonText: Check it out
    enable: yes
    subtitle: "Welcome to my portfolio website. Here you can find some work I have done on R while studying at London Business School."
    title: Welcome!
    url: blogs
